"""
Each new term in the Fibonacci sequence is 
generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose 
values do not exceed four million, find the sum of the even-valued terms.
"""
import time

start_time = time.time()
############################################

limit = 4000000
total = 0
cur = 0

def fib():
    a, b = 0, 1
    while 1:
        yield a
        a, b = b, a + b

gen = fib()

while cur <= limit:
    cur = next(gen)
    if cur % 2 == 0:
        total += cur

print('Total:', total)

############################################
print(time.time() - start_time, "seconds")